//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_project_mz6grm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Happiness15
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> Happiness_index15 { get; set; }
        public string Continent { get; set; }
    }
}
