//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_project_mz6grm
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email_Address { get; set; }
        public Nullable<int> Phone_Number { get; set; }
    }
}
